### ISSUE TITLE
yarn error: gatsby-plugin-shopify-metafields not found

### ISSUE THREAD

**Issue by ghost** [iamskok/gatsby-plugin-shopify-metafields#1]
Im trying to install your gatsby pluggin for a project I am working on, but it's failing to install and I see the following error. 
 ```
yarn add gatsby-plugin-shopify-metafields
```

```
An unexpected error occurred: "https://registry.yarnpkg.com/gatsby-plugin-shopify-metafields: Not found".
```

**Comment by iamskok** [comment]
@farreal Sorry for the late response. This package was never finished/published.
As a workaround, you can update the [`endpoint`](https://github.com/iamskok/gatsby-plugin-shopify-metafields/blob/master/src/lib.js#L27) and run `node src/lib.js`. You only need to do it once.
